const seedListings=[{id:1,title:'Paneer Rice & Curry',category:'Meals',quantity:'10 servings',quantityNumber:10,location:'T Nagar',description:'Surplus lunch food packed safely for community pickup.',pickup:'Today, 6:00 PM – 8:00 PM',donor:'Green Leaf Hostel'},{id:2,title:'Fresh Bread & Buns',category:'Bakery',quantity:'25 items',quantityNumber:25,location:'Adyar',description:'Fresh bakery items remaining at the end of the day.',pickup:'Today, 7:00 PM – 9:00 PM',donor:'Sunrise Bakery'},{id:3,title:'Vegetable Meals',category:'Meals',quantity:'8 meals',quantityNumber:8,location:'Velachery',description:'Healthy vegetarian meals available for immediate pickup.',pickup:'Today, 5:30 PM – 7:00 PM',donor:'Community Kitchen'},{id:4,title:'Chapati & Dal',category:'Meals',quantity:'12 servings',quantityNumber:12,location:'Guindy',description:'Surplus dinner portions packed and ready for collection.',pickup:'Today, 8:00 PM – 9:00 PM',donor:'City Hostel'},{id:5,title:'Fruit Boxes',category:'Fruits',quantity:'14 boxes',quantityNumber:14,location:'Anna Nagar',description:'Good-quality fruit boxes that need to be collected today.',pickup:'Today, 4:00 PM – 6:00 PM',donor:'Fresh Mart'},{id:6,title:'Idli & Sambar',category:'Meals',quantity:'20 servings',quantityNumber:20,location:'Mylapore',description:'Breakfast surplus packed into easy-to-carry portions.',pickup:'Today, 10:30 AM – 12:00 PM',donor:'Annapoorna Mess'}];
function getListings(){let x=JSON.parse(localStorage.getItem('pf_listings')||'null');if(!x){x=seedListings;saveListings(x)}return x}
function saveListings(x){localStorage.setItem('pf_listings',JSON.stringify(x))}
function getClaimed(){return JSON.parse(localStorage.getItem('pf_claimed')||'[]')}
function saveClaimed(x){localStorage.setItem('pf_claimed',JSON.stringify(x))}
function getAccounts(){return JSON.parse(localStorage.getItem('pf_accounts')||'[]')}
function saveAccounts(x){localStorage.setItem('pf_accounts',JSON.stringify(x))}
function currentUser(){return JSON.parse(localStorage.getItem('pf_user')||'null')}
function setCurrentUser(x){localStorage.setItem('pf_user',JSON.stringify(x))}
function logout(){localStorage.removeItem('pf_user');location.href='index.html'}
function requireLogin(){if(!currentUser()){location.href='auth.html?mode=login';return false}return true}
function requireRole(role){const u=currentUser();if(!u){location.href='auth.html?mode=login';return false}if(role&&u.role!==role){location.href=u.role==='donor'?'post.html':'browse.html';return false}return true}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function showToast(m){const t=document.querySelector('.toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function getStats(){const listings=getListings();const claimed=getClaimed();const donated=listings.filter(x=>x.donor==='Your listing').reduce((s,x)=>s+(Number(x.quantityNumber)||parseInt(x.quantity)||0),0);const claimedMeals=claimed.reduce((s,id)=>{const x=listings.find(v=>v.id===id);return s+(x?(Number(x.quantityNumber)||parseInt(x.quantity)||0):0)},0);const donorAccounts=getAccounts().filter(x=>x.role==='donor').length;const recipientAccounts=getAccounts().filter(x=>x.role==='receiver').length;return{meals:1200+donated+claimedMeals,donors:850+donorAccounts,recipients:420+recipientAccounts+claimed.length,tons:(2.5+(donated+claimedMeals)/400).toFixed(1)}}
function updateStats(){const s=getStats();document.querySelectorAll('[data-stat="meals"]').forEach(x=>x.textContent=s.meals.toLocaleString()+'+');document.querySelectorAll('[data-stat="donors"]').forEach(x=>x.textContent=s.donors.toLocaleString()+'+');document.querySelectorAll('[data-stat="recipients"]').forEach(x=>x.textContent=s.recipients.toLocaleString()+'+');document.querySelectorAll('[data-stat="tons"]').forEach(x=>x.textContent=s.tons+' tons')}
function setupNav(){const n=document.querySelector('.nav-links'),b=document.querySelector('.mobile-menu');if(b&&n)b.onclick=()=>n.classList.toggle('open');const u=currentUser();const nav=document.querySelector('.nav');if(!nav)return;if(u){const links=u.role==='donor'?[['post.html','Donate Food'],['mylistings.html','My Listings']]:[['browse.html','Find Food']];const existing=nav.querySelector('.nav-links');if(existing)existing.innerHTML=links.map(x=>`<a href="${x[0]}">${x[1]}</a>`).join('');const actions=nav.querySelector('.nav-actions');if(actions)actions.innerHTML=`<span class="profile-pill">${esc(u.name||u.email||u.phone)} <button class="logout" type="button">Log out</button></span>`;nav.querySelector('.logout')?.addEventListener('click',logout)}else{const existing=nav.querySelector('.nav-links');if(existing)existing.innerHTML='<a href="auth.html?mode=login">Log in</a><a href="auth.html?mode=signup">Sign up</a>';const actions=nav.querySelector('.nav-actions');if(actions)actions.innerHTML='<a class="btn btn-primary" href="auth.html?mode=signup">Get started</a>'}}
